# Tell Spring where to get the data from
spring:
    datasource:
        #postgres
        url: jdbc:postgresql://localhost:5432/vehicles
        username: postgres
        password: null1121                                  # entey your own password

    # jpa:
    #     database-platform: org.hibernate.dialect.H2Dialect      # tells spring data jpa that we're using h2 database
    #     defer-datasource-initialization: true                   # tells JPA to wait until hibernate has initialized before loading the data to h2

server:
    port: 8282     # changes port number for server