DROP TABLE IF EXISTS WAREHOUSE;
DROP TABLE IF EXISTS VEHICLE;

-- Table: WAREHOUSE
CREATE TABLE WAREHOUSE (
    warehouse_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
);

-- Table: VEHICLE

CREATE TABLE VEHICLE (
    vehicle_id SERIAL PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    color VARCHAR(255) NOT NULL,
    vin VARCHAR(255) UNIQUE NOT NULL,
    is_reserved BOOLEAN NOT NULL DEFAULT FALSE,
    is_soft_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    warehouse_id INTEGER REFERENCES WAREHOUSE(warehouse_id)
);
