DROP TABLE IF EXISTS WAREHOUSE;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS ADMINISTRATOR;
DROP TABLE IF EXISTS WAREHOUSE_ACCESS;

-- Table: WAREHOUSE
CREATE TABLE WAREHOUSE (
    warehouse_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    width DECIMAL(10, 2) NOT NULL,
    length DECIMAL(10, 2) NOT NULL,
    height DECIMAL(10, 2) NOT NULL
);

-- Table: VEHICLE
CREATE TABLE VEHICLE (
    vehicle_id SERIAL PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    color VARCHAR(255) NOT NULL,
    vin VARCHAR(255) UNIQUE NOT NULL,
    width DECIMAL(10, 2) NOT NULL,
    length DECIMAL(10, 2) NOT NULL,
    height DECIMAL(10, 2) NOT NULL,
    is_reserved BOOLEAN NOT NULL DEFAULT FALSE,
    is_soft_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    warehouse_id INTEGER REFERENCES WAREHOUSE(warehouse_id)
);

-- Table: ADMINISTRATOR
CREATE TABLE ADMINISTRATOR (
    admin_id SERIAL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- Table: WAREHOUSE_ACCESS
CREATE TABLE WAREHOUSE_ACCESS (
    access_id SERIAL PRIMARY KEY,
    admin_id INTEGER REFERENCES ADMINISTRATOR(admin_id),
    warehouse_id INTEGER REFERENCES WAREHOUSE(warehouse_id)
);